services:
  mongo:
    image: docker.io/library/mongo:7.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./.data/mongo:/data/db"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB: "logistics"
      PORT: "3000"
      PROVIDERS_TLS_BASEURL: "http://host.docker.internal:4010"
      PROVIDERS_NRW_BASEURL: "http://host.docker.internal:4020"
      POLL_CRON: "0 * * * *"
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"