services:
  mongo:
    image: docker.io/library/mongo:7.0.14
    # Si estás en Mac M1/M2 o ARM y te da problemas:
    # platform: linux/amd64
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./.data/mongo:/data/db"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"